cubo_semantico = {
    "Integer"=>  {
            "Integer"=>  {
                "+"=> "Integer", 
                "-"=> "Integer", 
                "*"=> "Integer", 
                "/"=> "Integer", 
                ">"=> "Boolean", 
                "<"=> "Boolean", 
                "="=> "Integer",
                "=="=>  "Boolean", 
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Float"=>  {
                "+"=> "Float", 
                "-"=> "Float", 
                "*"=> "Float", 
                "/"=> "Float", 
                ">"=> "Boolean",
                "<"=> "Boolean", 
                "="=> "Integer", 
                "=="=>  "Boolean",
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "String"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Boolean"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                },
            "Char"=> {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }
            }, 
        "Float"=> {
            "Integer"=>  {
                "+"=> "Float", 
                "-"=> "Float", 
                "*"=> "Float", 
                "/"=> "Float", 
                ">"=> "Boolean", 
                ">="=> "Boolean",
                "<="=> "Boolean",
                "<"=> "Boolean", 
                "="=> "Float",
                "=="=>  "Boolean", 
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Float"=>  {
                "+"=> "Float", 
                "-"=> "Float", 
                "*"=> "Float", 
                "/"=> "Float", 
                ">"=> "Boolean", 
                ">="=> "Boolean",
                "<="=> "Boolean",
                "<"=> "Boolean", 
                "="=> "Float", 
                "=="=>  "Boolean",
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Double"=>  {
                "+"=> "Double", 
                "-"=> "Double", 
                "*"=> "Double", 
                "/"=> "Double", 
                ">"=> "Boolean", 
                ">="=> "Boolean",
                "<="=> "Boolean",
                "<"=> "Boolean", 
                "="=> "Float",
                "=="=>  "Boolean", 
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "String"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error",
                "=="=>  "Error", 
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Boolean"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error",
                "=="=>  "Error", 
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                },
            "Char"=> {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }
            }, 
        "String"=> {
            "Integer"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Float"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "String"=>  {
                "+"=> "String", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "String", 
                "=="=>  "Boolean",
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Boolean"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                },
            "Char"=> {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }
            }, 
        "Boolean"=> {
            "Integer"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Float"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Double"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=> "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "String"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Error", 
                "=="=> "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Boolean"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Boolean", 
                "=="=> "Boolean",
                "<>"=> "Boolean",
                "and"=> "Boolean", 
                "or"=> "Boolean",
                },
            "Char"=> {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }
            },
        "Char"=>  {
            "Integer"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Float"=>  {
               "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "String"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                }, 
            "Boolean"=>  {
                "+"=> "Error", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                "<"=> "Error", 
                "="=> "Error", 
                "=="=>  "Error",
                "<>"=> "Error",
                "and"=> "Error", 
                "or"=> "Error",
                },
            "Char"=> {
                "+"=> "Char", 
                "-"=> "Error", 
                "*"=> "Error", 
                "/"=> "Error", 
                ">"=> "Error", 
                ">="=> "Error",
                "<="=> "Error",
                "<"=> "Error", 
                "="=> "Char", 
                "=="=>  "Boolean",
                "<>"=> "Boolean",
                "and"=> "Error", 
                "or"=> "Error",
                }
            },

        }

puts cubo_semantico["Char"]["Char"]["+"]

puts cubo_semantico["Integer"]["Integer"]["+"]

puts cubo_semantico["Boolean"]["Boolean"]["and"]

puts cubo_semantico["String"]["Char"]["+"]

puts cubo_semantico["Float"]["Float"]["+"]